displayName=Matching Lootbeams
author=bwl
support=https://github.com/blakelockley/runelite-matching-lootbeams/issues
description=Colors ground item loot beams using each item sprite's dominant color.
tags=ground,items,loot,beam,color
plugins=com.matchinglootbeams.MatchingLootbeamsPlugin
