displayName=Matching Lootbeams
author=blakos
description=Colors loot beams to match item's color
tags=ground,items,loot,beam,color
plugins=com.matchinglootbeams.MatchingLootbeamsPlugin
build=standard
